name: Playwright Full Suite Tests on 5 Shards

on:
  schedule:
    - cron: '0 9,21 * * *'  # Twice daily at 9 AM and 9 PM UTC

jobs:
  test:
    strategy:
      matrix:
        shard: [1, 2, 3, 4, 5]  # 5 shards (machines)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright Full Test Suite on Shard ${{ matrix.shard }}
        run: |
          npx playwright test --workers=3  # Running the full test suite with 3 workers in parallel
